import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import NavBar from "../components/NavBar";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: "Habitracker",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  // read light/dark mode cookie
  const cookieStore = await cookies();
  const mode = cookieStore.get("mode")?.value || "light"; // default to light mode

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${mode === "dark" ? "dark-mode" : ""}`}
      >
        {/* Insert custom nav-bar component */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
